---
- include_tasks: installer_version.yml

- name: 'Check if foreman_installer_options is a string'
  fail:
    msg: 'foreman_installer_options must be an array'
  when: foreman_installer_options is string

- name: 'Join options'
  set_fact:
    foreman_installer_options_joined: "{{ foreman_installer_options | join(' ') }} {{ foreman_installer_options_internal_use_only | join(' ') }}"

- name: 'Workaround facter\hostname'
  shell: "hostnamectl set-hostname $(/opt/puppetlabs/bin/facter fqdn)"
  become: true

- name: 'Generate /etc/hosts entry'
  shell: "echo $(ifconfig eth0 | grep inet | head -n1 | awk '{print $2}') $(hostname -f)"
  register: etchostsline

- name: 'Workaround etc/hosts'
  lineinfile:
    path: /etc/hosts
    insertbefore: BOF
    line: "{{ etchostsline.stdout }}"

- name: 'Install additional foreman_leapp system dependencies'
  yum:
    name: qpid-proton-c-devel
    state: present

- name: 'Run installer'
  shell: >
      {{ foreman_installer_command }} {{ (foreman_installer_verbose|bool) | ternary("-v", "") }}
      {{ (foreman_installer_no_colors|bool) | ternary("--no-colors", "") }}
      {{ (foreman_installer_disable_system_checks|bool) | ternary("--disable-system-checks", "") }}
      {{ foreman_installer_scenario_flag }} {{ foreman_installer_scenario }}
      {{ foreman_installer_options_joined }}
  when: not foreman_installer_skip_installer
  tags:
    - installation

- name: 'Workaround webpack (no dev server)'
  lineinfile:
    path: /home/vagrant/foreman/config/settings.yaml
    regexp: ':webpack_dev_server: true'
    line: ':webpack_dev_server: false'
  become: true

- name: 'Workaround: compile assets'
  shell: bash -lc 'bundle exec rake webpack:compile'
  args:
    chdir: "/home/vagrant/foreman"

- name: 'Install screen'
  yum:
    name: screen
    state: present
  become: true

- name: 'Start foreman in screen'
  shell: screen -S foreman -Ldm bash -lc "bundle exec rails s; sleep 2"
  args:
    chdir: "/home/vagrant/foreman"
